language: node_js
node_js:
  - 8

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.2
  - export PATH="$HOME/.yarn/bin:$PATH"


install:
  - npm install -g truffle@4.1.13
  - yarn install --frozen-lockfile

script:
  - yarn check --integrity && truffle compile && npm test

